// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectProfile(arg1) {
  return window['go']['main']['App']['ConnectProfile'](arg1);
}

export function DeletePassword(arg1) {
  return window['go']['main']['App']['DeletePassword'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DisconnectProfile(arg1) {
  return window['go']['main']['App']['DisconnectProfile'](arg1);
}

export function GetPassword(arg1) {
  return window['go']['main']['App']['GetPassword'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsProfileConnected(arg1) {
  return window['go']['main']['App']['IsProfileConnected'](arg1);
}

export function SavePassword(arg1, arg2) {
  return window['go']['main']['App']['SavePassword'](arg1, arg2);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}
