// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {discovery} from '../models';
import {profiles} from '../models';
import {history} from '../models';
import {queries} from '../models';
import {config} from '../models';

export function AddColumn(arg1:db.AddColumnParams):Promise<void>;

export function CancelQuery(arg1:string):Promise<boolean>;

export function CheckDangerousQuery(arg1:string):Promise<Record<string, any>>;

export function CheckDatabaseRestoreTarget(arg1:db.DatabaseRestoreParams):Promise<db.DatabaseRestorePreflightResult>;

export function CheckDatabaseTools():Promise<Record<string, boolean>>;

export function ClearQueryHistory():Promise<void>;

export function ConnectProfile(arg1:string):Promise<void>;

export function CreateEmptyDatabase(arg1:db.CreateDatabaseParams):Promise<void>;

export function CreateSchema(arg1:db.CreateSchemaParams):Promise<void>;

export function CreateTable(arg1:db.CreateTableParams):Promise<void>;

export function DeletePassword(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteQueryFolder(arg1:string):Promise<void>;

export function DeleteSavedQuery(arg1:string):Promise<void>;

export function DeleteTableRow(arg1:db.DeleteRowParams):Promise<void>;

export function DisconnectProfile(arg1:string):Promise<void>;

export function DiscoverDockerDatabases():Promise<Array<discovery.DockerDatabaseInfo>>;

export function DiscoverLocalDatabases():Promise<Array<discovery.LocalDatabaseInfo>>;

export function DropColumn(arg1:db.DropColumnParams):Promise<void>;

export function DropDatabase(arg1:db.DropDatabaseParams):Promise<void>;

export function DropSchema(arg1:db.DropSchemaParams):Promise<void>;

export function DropTable(arg1:db.DropTableParams):Promise<void>;

export function ExportDatabaseSQL(arg1:db.DatabaseBackupParams):Promise<db.DatabaseOperationResult>;

export function ExportQueryResults(arg1:string,arg2:db.QueryResult):Promise<db.DatabaseOperationResult>;

export function GetDatabases(arg1:string):Promise<Array<db.DatabaseInfo>>;

export function GetProfile(arg1:string):Promise<profiles.Profile>;

export function GetProfiles():Promise<Array<profiles.Profile>>;

export function GetQueryHistory():Promise<Array<history.HistoryEntry>>;

export function GetSavedQueries():Promise<queries.SavedQueries>;

export function GetSchemas(arg1:string,arg2:string):Promise<Array<db.SchemaInfo>>;

export function GetSettings():Promise<config.Settings>;

export function GetTableColumns(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<db.ColumnDef>>;

export function GetTableForeignKeys(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<db.ForeignKeyInfo>>;

export function GetTableIndexes(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<db.TableIndexInfo>>;

export function GetTablePage(arg1:db.TablePageParams):Promise<db.TablePageResult>;

export function GetTables(arg1:string,arg2:string,arg3:string):Promise<Array<db.TableInfo>>;

export function Greet(arg1:string):Promise<string>;

export function ImportDatabaseSQL(arg1:db.DatabaseRestoreParams):Promise<db.DatabaseOperationResult>;

export function InsertTableRow(arg1:db.InsertRowParams):Promise<void>;

export function IsProfileConnected(arg1:string):Promise<boolean>;

export function RefreshDockerDiscovery():Promise<Array<discovery.DockerDatabaseInfo>>;

export function RefreshLocalDiscovery():Promise<Array<discovery.LocalDatabaseInfo>>;

export function RenameColumn(arg1:db.RenameColumnParams):Promise<void>;

export function RenameTable(arg1:db.RenameTableParams):Promise<void>;

export function RunQuery(arg1:db.QueryExecutionParams):Promise<db.QueryResult>;

export function RunQueryWithCancellation(arg1:db.QueryExecutionParams,arg2:string):Promise<db.QueryResult>;

export function SavePassword(arg1:string,arg2:string):Promise<void>;

export function SaveProfile(arg1:profiles.Profile):Promise<profiles.Profile>;

export function SaveQueryFolder(arg1:queries.Folder):Promise<void>;

export function SaveSavedQuery(arg1:queries.SavedQuery):Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function TestConnection(arg1:string):Promise<void>;

export function TestProfileConnection(arg1:db.ConnectionTestParams):Promise<db.ConnectionTestResult>;

export function UpdateProfile(arg1:profiles.Profile):Promise<void>;

export function UpdateTableRow(arg1:db.UpdateRowParams):Promise<void>;
