// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearQueryHistory() {
  return window['go']['main']['App']['ClearQueryHistory']();
}

export function ConnectProfile(arg1) {
  return window['go']['main']['App']['ConnectProfile'](arg1);
}

export function DeletePassword(arg1) {
  return window['go']['main']['App']['DeletePassword'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteQueryFolder(arg1) {
  return window['go']['main']['App']['DeleteQueryFolder'](arg1);
}

export function DeleteSavedQuery(arg1) {
  return window['go']['main']['App']['DeleteSavedQuery'](arg1);
}

export function DeleteTableRow(arg1) {
  return window['go']['main']['App']['DeleteTableRow'](arg1);
}

export function DisconnectProfile(arg1) {
  return window['go']['main']['App']['DisconnectProfile'](arg1);
}

export function GetDatabases(arg1) {
  return window['go']['main']['App']['GetDatabases'](arg1);
}

export function GetPassword(arg1) {
  return window['go']['main']['App']['GetPassword'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetQueryHistory() {
  return window['go']['main']['App']['GetQueryHistory']();
}

export function GetSavedQueries() {
  return window['go']['main']['App']['GetSavedQueries']();
}

export function GetSchemas(arg1, arg2) {
  return window['go']['main']['App']['GetSchemas'](arg1, arg2);
}

export function GetTableColumns(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableColumns'](arg1, arg2, arg3);
}

export function GetTableForeignKeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableForeignKeys'](arg1, arg2, arg3);
}

export function GetTableIndexes(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableIndexes'](arg1, arg2, arg3);
}

export function GetTablePage(arg1) {
  return window['go']['main']['App']['GetTablePage'](arg1);
}

export function GetTables(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTables'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InsertTableRow(arg1) {
  return window['go']['main']['App']['InsertTableRow'](arg1);
}

export function IsProfileConnected(arg1) {
  return window['go']['main']['App']['IsProfileConnected'](arg1);
}

export function RunQuery(arg1) {
  return window['go']['main']['App']['RunQuery'](arg1);
}

export function SavePassword(arg1, arg2) {
  return window['go']['main']['App']['SavePassword'](arg1, arg2);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveQueryFolder(arg1) {
  return window['go']['main']['App']['SaveQueryFolder'](arg1);
}

export function SaveSavedQuery(arg1) {
  return window['go']['main']['App']['SaveSavedQuery'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}

export function UpdateTableRow(arg1) {
  return window['go']['main']['App']['UpdateTableRow'](arg1);
}
