// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {profiles} from '../models';

export function ConnectProfile(arg1:string):Promise<void>;

export function DeletePassword(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DisconnectProfile(arg1:string):Promise<void>;

export function GetDatabases(arg1:string):Promise<Array<db.DatabaseInfo>>;

export function GetPassword(arg1:string):Promise<string>;

export function GetProfile(arg1:string):Promise<profiles.Profile>;

export function GetProfiles():Promise<Array<profiles.Profile>>;

export function GetSchemas(arg1:string,arg2:string):Promise<Array<db.SchemaInfo>>;

export function GetTableColumns(arg1:string,arg2:string,arg3:string):Promise<Array<db.ColumnDef>>;

export function GetTablePage(arg1:db.TablePageParams):Promise<db.TablePageResult>;

export function GetTables(arg1:string,arg2:string,arg3:string):Promise<Array<db.TableInfo>>;

export function Greet(arg1:string):Promise<string>;

export function IsProfileConnected(arg1:string):Promise<boolean>;

export function SavePassword(arg1:string,arg2:string):Promise<void>;

export function SaveProfile(arg1:profiles.Profile):Promise<profiles.Profile>;

export function TestConnection(arg1:string):Promise<void>;

export function UpdateProfile(arg1:profiles.Profile):Promise<void>;
